[package]
name = "duckdb_bigtable2_rust"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "duckdb_bigtable2_rust"
crate-type = ["staticlib"]

[dependencies]
duckdb = { version = "1.0", features = ["vtab"] }
